### ISSUE TITLE
module design

### ISSUE THREAD

**Issue by ungoldman** [moose-team/peerbot#2]
This seems to be running fine without globally installed `electron-prebuilt` & `electron-spawn`.

Tested on two machines after `npm uninstall -g electron-prebuilt electron-spawn`.

Other than the undesirable requirement of a large download during the `npm install` step, this seems to be in working shape.

Wanted to open it up for discussion in case I'm missing something as I know @maxogden had reservations about doing it this way.

_edit: this is a bad idea_

**Comment by ungoldman** [comment]
Actually thinking about it now it would probably make more sense for it to work this way:

``` bash
$ npm install -g peerbot electron-prebuilt electron-spawn
# peerbot rebuilds leveldb automatically on postinstall
$ peerbot --channel=cats
# run `peerbot rebuild` as necessary if db changes occur
```

**Comment by ungoldman** [comment]
Took a first pass at something that would work as noted above on the cli branch:

https://github.com/moose-team/peerbot/tree/cli

Works when running as `./bin/cli` locally but fails when trying to run globally after `npm link`:

```
∴ ng@crimelab ~/dev/github/peerbot (cli) $ peerbot
dyld: lazy symbol binding failed: Symbol not found: __ZN2v89Signature3NewEPNS_7IsolateENS_6HandleINS_16FunctionTemplateEEE
  Referenced from: /Users/ng/dev/github/peerbot/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v89Signature3NewEPNS_7IsolateENS_6HandleINS_16FunctionTemplateEEE
  Referenced from: /Users/ng/dev/github/peerbot/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

**Comment by Flet** [comment]
FYI master works for me without global electron-prebuilt & electron-spawn.

**Comment by ungoldman** [comment]
@Flet thanks! Still want to figure out how to make this `npm install`able so you can just `npm install -g peerbot` then run `peerbot` and have a channel seeding bot with as little extra work as possible.

**Comment by Flet** [comment]
trying the cli branch and I had to do this:

```
  "bin": {
    "peerbot": "bin/cli"
  },
```

and I get 

```
/home/flet/npm/bin/peerbot: 3: /home/flet/npm/bin/peerbot: electron-spawn: not found
```

So, doing this:

```
npm install -g electron-prebuilt electron-spawn
```

then running `peerbot` and its running.

**Comment by ungoldman** [comment]
@Flet really? I got the error mentioned above when doing that (https://github.com/moose-team/peerbot/issues/2#issuecomment-97696005)

I added some doc anticipating it working here: https://github.com/moose-team/peerbot/tree/cli#install

I'll try it again locally, maybe I got lucky and the error was due to me messing with leveldb and modules and node versions a lot.

**Comment by ungoldman** [comment]
ooooh I totally filtered out the first thing you said re: `"peerbot": "bin/cli"` -- I thought I had already written it that way. Thanks! I think I can publish this. Will test a couple more times then merge and push to npm.

**Comment by Flet** [comment]
Sorry I should have pushed that :)

**Comment by ungoldman** [comment]
only works in peerbot directory right now, forgot the shell script will run `electron-spawn . $@` in the context of current working directory.

**Comment by ungoldman** [comment]
@Flet I just pushed something that might work, would you mind pulling down the `cli` branch and installing, npm linking, and trying to run the peerbot command in another directory to see if it actually works?

**Comment by Flet** [comment]
Does not work with latest cli branch in another directory: 

```
dan@wonderbread:~/code$ peerbot
[26346:0430/161429:ERROR:browser_main_loop.cc(171)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[26376:0430/161430:INFO:renderer_main.cc(200)] Renderer process started
[26346:0430/161430:INFO:CONSOLE(326)] "Uncaught Error: Cannot find module '/home/dan/code'", source: module.js (326)
```

**Comment by ungoldman** [comment]
:( thanks for trying

**Comment by ungoldman** [comment]
I think the way https://github.com/maxogden/electron-spawn consumes the path arg is relative-only... anyway I think I have a workaround now.

**Comment by ungoldman** [comment]
working!

```
npm i -g electron-prebuilt electron-spawn peerbot
peerbot
```

:penguin:
